"""Add api_logs table

Revision ID: 20f45f250e19
Revises: d20db02b88e3
Create Date: 2025-12-19 11:06:03.359175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20f45f250e19"
down_revision: Union[str, None] = "d20db02b88e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=True),
        sa.Column("webhook_secret", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_key"),
    )
    op.create_index(op.f("ix_operators_id"), "operators", ["id"], unique=False)
    op.create_index(
        op.f("ix_operators_name"), "operators", ["name"], unique=True
    )
    op.create_table(
        "api_logs",
        sa.Column(
            "api_log_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_ms", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("voyage_id", sa.Integer(), nullable=True),
        sa.Column("ip_hash", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.id"],
        ),
        sa.PrimaryKeyConstraint("api_log_id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(
        op.f("ix_api_logs_api_log_id"),
        "api_logs",
        ["api_log_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_logs_api_log_id"), table_name="api_logs")
    op.drop_table("api_logs")
    op.drop_index(op.f("ix_operators_name"), table_name="operators")
    op.drop_index(op.f("ix_operators_id"), table_name="operators")
    op.drop_table("operators")
    # ### end Alembic commands ###
