"""add voyage_speed_estimate table

Revision ID: 2cfb55c0d184
Revises: e64d85d567de
Create Date: 2025-12-30 10:05:13.747608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cfb55c0d184"
down_revision: Union[str, None] = "e64d85d567de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voyage_speed_estimates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("voyage_id", sa.Integer(), nullable=False),
        sa.Column("profile", sa.String(), nullable=False),
        sa.Column(
            "speed_knots", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "expected_emissions_kg_co2",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column(
            "expected_arrival_delay_minutes", sa.Integer(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "profile IN ('eco','standard','fast')", name="ck_profile_valid"
        ),
        sa.ForeignKeyConstraint(
            ["voyage_id"], ["voyages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("voyage_id", "profile", name="uq_voyage_profile"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voyage_speed_estimates")
    # ### end Alembic commands ###
