"""add_updated_at_to_widget_configs

Revision ID: 466c379e2453
Revises: 47a6dcb1db34
Create Date: 2026-03-01 19:06:06.354560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "466c379e2453"
down_revision: Union[str, None] = "47a6dcb1db34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "widget_configs",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("widget_configs", "updated_at")
    # ### end Alembic commands ###
