"""Voyage_id FK to api_log

Revision ID: 5618b18b18e7
Revises: a1c90a6f873b
Create Date: 2026-01-31 11:54:49.327609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5618b18b18e7"
down_revision: Union[str, None] = "a1c90a6f873b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_api_logs_operator_id"),
        "api_logs",
        ["operator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_logs_user_id"), "api_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_logs_voyage_id"), "api_logs", ["voyage_id"], unique=False
    )
    op.drop_constraint(
        "fk_api_logs_user_id_users", "api_logs", type_="foreignkey"
    )
    op.drop_constraint(
        "api_logs_operator_id_fkey", "api_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "api_logs",
        "operators",
        ["operator_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "api_logs", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "api_logs", "voyages", ["voyage_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_logs", type_="foreignkey")
    op.drop_constraint(None, "api_logs", type_="foreignkey")
    op.drop_constraint(None, "api_logs", type_="foreignkey")
    op.create_foreign_key(
        "api_logs_operator_id_fkey",
        "api_logs",
        "operators",
        ["operator_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_api_logs_user_id_users", "api_logs", "users", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_api_logs_voyage_id"), table_name="api_logs")
    op.drop_index(op.f("ix_api_logs_user_id"), table_name="api_logs")
    op.drop_index(op.f("ix_api_logs_operator_id"), table_name="api_logs")
    # ### end Alembic commands ###
