"""Replace voyage estimates with ship route anchors

Revision ID: 745f2f610203
Revises: 505e8a148471
Create Date: 2026-01-16 09:51:17.256868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "745f2f610203"
down_revision: Union[str, None] = "505e8a148471"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speed_to_emissions_estimates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("ship_id", sa.Integer(), nullable=False),
        sa.Column("profile", sa.String(), nullable=False),
        sa.Column(
            "speed_knots", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "expected_emissions_kg_co2",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column(
            "expected_arrival_delta_minutes", sa.Integer(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "profile IN ('eco','standard','fast')",
            name="ck_speed_estimates_profile",
        ),
        sa.CheckConstraint(
            "expected_emissions_kg_co2 >= 0",
            name="ck_speed_estimates_emissions_non_negative",
        ),
        sa.CheckConstraint(
            "speed_knots > 0", name="ck_speed_estimates_speed_positive"
        ),
        sa.ForeignKeyConstraint(
            ["route_id"], ["routes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["ship_id"], ["ships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "route_id",
            "ship_id",
            "profile",
            name="uq_speed_estimates_route_ship_profile",
        ),
    )
    op.create_index(
        op.f("ix_speed_to_emissions_estimates_route_id"),
        "speed_to_emissions_estimates",
        ["route_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_speed_to_emissions_estimates_ship_id"),
        "speed_to_emissions_estimates",
        ["ship_id"],
        unique=False,
    )
    op.drop_table("voyage_speed_estimates")
    op.add_column(
        "voyages", sa.Column("route_id", sa.Integer(), nullable=True)
    )
    op.add_column("voyages", sa.Column("ship_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_voyages_route_id"), "voyages", ["route_id"], unique=False
    )
    op.create_index(
        op.f("ix_voyages_ship_id"), "voyages", ["ship_id"], unique=False
    )
    op.create_foreign_key(
        None, "voyages", "routes", ["route_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "voyages", "ships", ["ship_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "voyages", type_="foreignkey")
    op.drop_constraint(None, "voyages", type_="foreignkey")
    op.drop_index(op.f("ix_voyages_ship_id"), table_name="voyages")
    op.drop_index(op.f("ix_voyages_route_id"), table_name="voyages")
    op.drop_column("voyages", "ship_id")
    op.drop_column("voyages", "route_id")
    op.create_table(
        "voyage_speed_estimates",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "voyage_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "profile", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "speed_knots",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expected_emissions_kg_co2",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expected_arrival_delay_minutes",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "profile::text = ANY (ARRAY['eco'::character varying, 'standard'::character varying, 'fast'::character varying]::text[])",
            name="ck_profile_valid",
        ),
        sa.ForeignKeyConstraint(
            ["voyage_id"],
            ["voyages.id"],
            name="voyage_speed_estimates_voyage_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="voyage_speed_estimates_pkey"),
        sa.UniqueConstraint(
            "voyage_id",
            "profile",
            name="uq_voyage_profile",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_index(
        op.f("ix_speed_to_emissions_estimates_ship_id"),
        table_name="speed_to_emissions_estimates",
    )
    op.drop_index(
        op.f("ix_speed_to_emissions_estimates_route_id"),
        table_name="speed_to_emissions_estimates",
    )
    op.drop_table("speed_to_emissions_estimates")
    # ### end Alembic commands ###
