"""add_voyage_creation_rules

Revision ID: 768963b98209
Revises: b6ce31089254
Create Date: 2026-02-28 11:25:06.397649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "768963b98209"
down_revision: Union[str, None] = "b6ce31089254"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voyage_creation_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("ship_id", sa.Integer(), nullable=False),
        sa.Column("widget_config_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["operators.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["route_id"], ["routes.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ship_id"], ["ships.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["widget_config_id"], ["widget_configs.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voyage_creation_rules_operator_id"),
        "voyage_creation_rules",
        ["operator_id"],
        unique=False,
    )
    op.add_column(
        "voyages",
        sa.Column("voyage_creation_rule_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "voyages",
        "voyage_creation_rules",
        ["voyage_creation_rule_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "voyages", type_="foreignkey")
    op.drop_column("voyages", "voyage_creation_rule_id")
    op.drop_index(
        op.f("ix_voyage_creation_rules_operator_id"),
        table_name="voyage_creation_rules",
    )
    op.drop_table("voyage_creation_rules")
    # ### end Alembic commands ###
