"""Added API_LOG FK to users table

Revision ID: 81dae069bc8b
Revises: e116d0ed950e
Create Date: 2025-12-27 10:06:51.906570

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81dae069bc8b"
down_revision: Union[str, None] = "e116d0ed950e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility (recreates table with FK)
    with op.batch_alter_table("api_logs") as batch_op:
        batch_op.create_foreign_key(
            "fk_api_logs_user_id_users", "users", ["user_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_logs") as batch_op:
        batch_op.drop_constraint(
            "fk_api_logs_user_id_users", table_name="api_logs", type_="foreignkey"
        )
    # ### end Alembic commands ###
