"""add confirmed_choices table

Revision ID: 8cbf8f5d93c7
Revises: c7b666a15d9f
Create Date: 2026-01-08 11:04:19.402277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cbf8f5d93c7"
down_revision: Union[str, None] = "c7b666a15d9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "confirmed_choices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("voyage_id", sa.Integer(), nullable=False),
        sa.Column("intent_id", sa.String(), nullable=True),
        sa.Column("booking_id", sa.String(), nullable=False),
        sa.Column(
            "slider_value", sa.Numeric(precision=4, scale=3), nullable=False
        ),
        sa.Column(
            "delta_pct_from_standard",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "selected_speed_kn",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "confirmed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confirmed_at IS NOT NULL",
            name="ck_confirmed_choices_confirmed_at_not_null",
        ),
        sa.CheckConstraint(
            "delta_pct_from_standard >= -100 AND delta_pct_from_standard <= 100",
            name="ck_confirmed_choices_delta_pct_range",
        ),
        sa.CheckConstraint(
            "slider_value >= 0 AND slider_value <= 1",
            name="ck_confirmed_choices_slider_range",
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"], ["choice_intents.intent_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["voyage_id"], ["voyages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "voyage_id",
            "booking_id",
            name="uq_confirmed_choices_voyage_booking",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("confirmed_choices")
    # ### end Alembic commands ###
