"""add voyages table

Revision ID: 9be90b89c189
Revises: 26672fcf2636
Create Date: 2025-12-28 16:21:41.893832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9be90b89c189"
down_revision: Union[str, None] = "26672fcf2636"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voyages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("external_trip_id", sa.String(), nullable=True),
        sa.Column("departure_port", sa.String(), nullable=True),
        sa.Column("arrival_port", sa.String(), nullable=True),
        sa.Column("departure_datetime", sa.TIMESTAMP(), nullable=False),
        sa.Column("arrival_datetime", sa.TIMESTAMP(), nullable=False),
        sa.Column("route_geometry", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["operators.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voyages")
    # ### end Alembic commands ###
