"""make_voyage_external_trip_id_and_widget_config_id_non_nullable

Revision ID: 9df85cdffc39
Revises: 768963b98209
Create Date: 2026-02-28 14:47:50.613037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9df85cdffc39"
down_revision: Union[str, None] = "768963b98209"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "voyages",
        "external_trip_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "voyages",
        "widget_config_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        "voyages_widget_config_id_fkey", "voyages", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "voyages",
        "widget_configs",
        ["widget_config_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "voyages", type_="foreignkey")
    op.create_foreign_key(
        "voyages_widget_config_id_fkey",
        "voyages",
        "widget_configs",
        ["widget_config_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "voyages",
        "widget_config_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "voyages",
        "external_trip_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
