"""add_duration_nights_to_routes

Revision ID: b6ce31089254
Revises: 5618b18b18e7
Create Date: 2026-02-28 10:17:36.711895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6ce31089254"
down_revision: Union[str, None] = "5618b18b18e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routes",
        sa.Column(
            "duration_nights",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "duration_nights")
    # ### end Alembic commands ###
