"""add choice_intents table

Revision ID: c7b666a15d9f
Revises: 7f8b86dc3d8b
Create Date: 2026-01-06 12:41:55.202487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7b666a15d9f"
down_revision: Union[str, None] = "7f8b86dc3d8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "choice_intents",
        sa.Column("intent_id", sa.String(), nullable=False),
        sa.Column("voyage_id", sa.Integer(), nullable=False),
        sa.Column(
            "slider_value", sa.Numeric(precision=4, scale=3), nullable=False
        ),
        sa.Column(
            "delta_pct_from_standard",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "selected_speed_kn",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column("consumed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "delta_pct_from_standard >= -100 AND delta_pct_from_standard <= 100",
            name="ck_intent_delta_pct_range",
        ),
        sa.CheckConstraint(
            "slider_value >= 0 AND slider_value <= 1",
            name="ck_intent_slider_range",
        ),
        sa.ForeignKeyConstraint(
            ["voyage_id"], ["voyages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("intent_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("choice_intents")
    # ### end Alembic commands ###
