"""add unique constraint on operator_id and external_trip_id

Revision ID: e64d85d567de
Revises: 9be90b89c189
Create Date: 2025-12-28 16:35:00.370100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e64d85d567de"
down_revision: Union[str, None] = "9be90b89c189"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_operator_external_trip",
        "voyages",
        ["operator_id", "external_trip_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_operator_external_trip", "voyages", type_="unique")
    # ### end Alembic commands ###
